services:
  - type: web
    name: ai-chatbot-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: chatbot-db
          property: connectionString
      - key: PYTHON_VERSION
        value: 3.11.0

  - type: web
    name: ai-chatbot-frontend
    env: node
    buildCommand: cd frontend && npm ci && npm run build
    startCommand: cd frontend && npm start
    envVars:
      - key: NEXT_PUBLIC_API_URL
        value: https://ai-chatbot-backend.onrender.com

databases:
  - name: chatbot-db
    databaseName: chatbotdb
    user: chatbot_user